import ignoreComponentes from './ignoreComponentes';
import ignoreComponentesCustom from './ignoreComponentesCustom';
export default {
  servidorselect: ignoreComponentesCustom,
  unidadeselect: ignoreComponentesCustom,
  partesetpselect: ignoreComponentesCustom,
  processoSeiTextField: ignoreComponentes,
  tipoconstratacaoselect: ignoreComponentesCustom,
  textfield: ignoreComponentes,
  textarea: ignoreComponentes,
  email: ignoreComponentes,
  number: ignoreComponentes,
  password: ignoreComponentes,
  checkbox: ignoreComponentes,
  time: ignoreComponentes,
  select: ignoreComponentes,
  radio: ignoreComponentes,
  button: ignoreComponentes,
  selectboxes: ignoreComponentes,
  url: ignoreComponentes,
  tags: ignoreComponentes,
  address: ignoreComponentes,
  datagrid: ignoreComponentes,
  survey: ignoreComponentes,
  currency: ignoreComponentes,
  signature: ignoreComponentes,
  day: ignoreComponentes,
  phoneNumber: ignoreComponentes,
  datetime: ignoreComponentes,
  panel: ignoreComponentes,
  table: ignoreComponentes,
  tabs: ignoreComponentes,
  well: ignoreComponentes,
  columns: ignoreComponentes,
  fieldset: ignoreComponentes,
  botaoajuda: ignoreComponentes,
  textoajuda: ignoreComponentes,
  notainterna: ignoreComponentes,
  content: [
    ...ignoreComponentes,
    {
      key: 'display',
      components: [
        {
          key: 'modalEdit',
          ignore: true,
        },
      ],
    },
  ],
  htmlelement: ignoreComponentes,
  hidden: ignoreComponentes,
};
